#!/usr/bin/env python3
"""
tests/gen_write_map.py  v4.0
Generates docs/WRITE_MAP.md — what every box writes, and who writes it.

v4.0  2026-08-25  Operator's ask: "a document that answers what does every box
write and who writes it — like a file map, but for journal writers."

WHY IT IS SEPARATE FROM FILE_MAP.md. That map answers "what calls what" from
the import graph. This answers a different question the import graph cannot:
**which module OWNS which table.** By r70 this repo had 22 tables across three
databases and NO SINGLE INDEX of who writes them — the ownership lived only in
scattered docstrings, which is the same shape as the sensor problem: a thing
that exists with no way to see it whole.

⚠️ GENERATED, NEVER HAND-MAINTAINED. A hand-kept write map drifts exactly the
way the version headers drifted across day_trader_pro — the changelogs advanced
while the title lines went stale for weeks. This is regenerated in the gate.

⚠️ IT REPORTS WHAT THE SOURCE SAYS, NOT WHAT A SCHEMA DUMP SAYS. A live
database shows tables that exist; this shows tables the CODE creates and
writes. The difference is the interesting part — a table in the db with no
writer in the tree is an orphan, and a writer whose table nobody reads is dead
weight. Both are visible here and in neither place alone.

Run:  python3 tests/gen_write_map.py           # regenerate
      python3 tests/gen_write_map.py --check   # fail if stale
"""

from __future__ import annotations

import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "docs", "WRITE_MAP.md")

SKIP_DIRS = {".git", "__pycache__", "venv", "docs", "node_modules"}

RE_CREATE = re.compile(r"CREATE TABLE IF NOT EXISTS\s+([a-z_]+)", re.I)
RE_INSERT = re.compile(r"INSERT\s+(?:OR\s+\w+\s+)?INTO\s+([a-z_]+)", re.I)
RE_UPDATE = re.compile(r"UPDATE\s+([a-z_]+)\s+SET", re.I)
RE_DELETE = re.compile(r"DELETE\s+FROM\s+([a-z_]+)", re.I)
RE_SELECT = re.compile(r"FROM\s+([a-z_]+)", re.I)
RE_DBFILE = re.compile(r"([a-z_]+)\.db")

# Which database each table lives in. Derived from the module that CREATEs it,
# so a table moving file moves here automatically.
DB_OF_DIR = {
    "data/candle_feed.py": "feed_store.db",
    "data/derived_store.py": "derived_store.db",
    "database/trade_logger.py": "trades.db",
}

# ⚠️ MODULES THAT CREATE THEIR OWN TABLE INSIDE ANOTHER STORE'S FILE.
# `derived/` engines call `self._store.conn.execute("CREATE TABLE ...")` so the
# table lives in derived_store.db while the DDL lives in the engine. That is
# deliberate — one engine per store, each owning its own schema — but it means
# the file that CREATEs is not the file that names the database, and the first
# run of this generator listed four tables as "(unattributed)". Reporting them
# as homeless would be wrong; guessing silently would be worse. This is the
# explicit mapping, and it is the ONE hand-maintained thing here.
DB_OF_PREFIX = {
    "derived/": "derived_store.db",
    "analysis/tenor_publish.py": "feed_store.db",
}


def _files():
    for dp, dn, fn in os.walk(ROOT):
        dn[:] = [d for d in dn if d not in SKIP_DIRS]
        for f in sorted(fn):
            if f.endswith(".py"):
                yield os.path.relpath(os.path.join(dp, f), ROOT)


def scan():
    creates, writes, reads, dbs = {}, {}, {}, {}
    for rel in _files():
        try:
            src = open(os.path.join(ROOT, rel), encoding="utf-8").read()
        except Exception:                                       # noqa: BLE001
            continue
        for t in RE_CREATE.findall(src):
            creates.setdefault(t, set()).add(rel)
            if rel in DB_OF_DIR:
                dbs[t] = DB_OF_DIR[rel]
            else:
                for pref, db in DB_OF_PREFIX.items():
                    if rel.startswith(pref):
                        dbs[t] = db
                        break
        for rx, kind in ((RE_INSERT, "insert"), (RE_UPDATE, "update"),
                         (RE_DELETE, "delete")):
            for t in rx.findall(src):
                writes.setdefault(t, {}).setdefault(rel, set()).add(kind)
        for t in RE_SELECT.findall(src):
            # a module that only writes also names the table in its INSERT;
            # reads are recorded separately so "who consumes this" is answerable
            if t in creates or t in writes or t in reads:
                reads.setdefault(t, set()).add(rel)
        for d in RE_DBFILE.findall(src):
            if d in ("self", "args", "d"):
                continue
    return creates, writes, reads, dbs


def render() -> str:
    creates, writes, reads, dbs = scan()
    tables = sorted(set(creates) | set(writes))
    L = []
    L.append("# WRITE_MAP.md — what every box writes, and who writes it")
    L.append("")
    L.append("**GENERATED by `tests/gen_write_map.py` — do not edit by hand.**")
    L.append("Regenerated in the land gate; a stale map fails `--check`.")
    L.append("")
    L.append("`FILE_MAP.md` answers *what calls what*. This answers *who owns "
             "which table* — a question the import graph cannot.")
    L.append("")
    L.append("⚠️ **A table with no writer is an orphan. A table nobody reads "
             "is dead weight.** Both are visible here and in neither the "
             "schema nor the call graph alone.")
    L.append("")
    L.append(f"**{len(tables)} tables.**")
    L.append("")

    by_db = {}
    for t in tables:
        by_db.setdefault(dbs.get(t, "(unattributed)"), []).append(t)

    for db in sorted(by_db):
        L.append(f"## {db}")
        L.append("")
        L.append("| table | created by | written by | read by |")
        L.append("|---|---|---|---|")
        for t in sorted(by_db[db]):
            c = ", ".join(f"`{x}`" for x in sorted(creates.get(t, []))) or "—"
            w = writes.get(t, {})
            wparts = []
            for mod in sorted(w):
                kinds = "/".join(sorted(w[mod]))
                wparts.append(f"`{mod}` ({kinds})")
            wtxt = ", ".join(wparts) or "**— NO WRITER**"
            r = sorted(x for x in reads.get(t, set())
                       if x not in w and x not in creates.get(t, set()))
            rtxt = ", ".join(f"`{x}`" for x in r) or "—"
            L.append(f"| `{t}` | {c} | {wtxt} | {rtxt} |")
        L.append("")

    orphan_w = [t for t in tables if not writes.get(t)]
    orphan_r = [t for t in tables
                if not [x for x in reads.get(t, set())
                        if x not in writes.get(t, {})]]
    L.append("## Flags")
    L.append("")
    L.append(f"- **No writer** ({len(orphan_w)}): "
             + (", ".join(f"`{t}`" for t in orphan_w) or "none"))
    L.append(f"- **No external reader** ({len(orphan_r)}): "
             + (", ".join(f"`{t}`" for t in orphan_r) or "none"))
    L.append("")
    L.append("⚠️ *No external reader* is not automatically a defect — a table "
             "written today for a study run in a month is exactly the point of "
             "the derived layer. It IS a defect when nobody ever intends to "
             "read it, and this list is where that question gets asked.")
    L.append("")
    return "\n".join(L)


def main() -> int:
    text = render()
    if "--check" in sys.argv:
        try:
            cur = open(OUT, encoding="utf-8").read()
        except FileNotFoundError:
            print("  WRITE_MAP.md missing — run gen_write_map.py")
            return 1
        if cur.strip() != text.strip():
            print("  WRITE_MAP.md is STALE — regenerate it")
            return 1
        print("  write map is current")
        return 0
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(text)
    print(f"  wrote {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
